export const characters = [
  {
    id: 1,
    name: "Viking",
    sprite: "/NorthernHuman.png",
    hitbox: {
      width: 40,
      height: 60,
      offsetX: 35,
      offsetY: 15,
    },
    hp: 120,
    mp: 0,
    movementSpeed: 3,
    attackSpeed: 1.2,
    weapons: [],
  },
  {
    id: 2,
    name: "Thrall",
    sprite: "/Dwarf.png",
    hitbox: { width: 40, height: 60 },
    hp: 50,
    mp: 0,
    movementSpeed: 2,
    attackSpeed: 1.2,
    weapons: [],
  },
  {
    id: 3,
    name: "Thrall",
    sprite: "/Dwarf.png",
    hitbox: { width: 40, height: 60 },
    hp: 50,
    mp: 0,
    movementSpeed: 2,
    attackSpeed: 1.2,
    weapons: [],
  },
  {
    id: 4,
    name: "Thrall",
    sprite: "/Dwarf.png",
    hitbox: { width: 40, height: 60 },
    hp: 50,
    mp: 0,
    movementSpeed: 2,
    attackSpeed: 1.2,
    weapons: [],
  },
];
